In [ ]:
import pandas as pd
import numpy as np

# ✅ 📘 Part A: Handling Missing Values
### 🔹 Q1. Identify missing values and provide a summary report
**✅ Answer:**

Missing values are the data points that are not recorded or appear as null/NaN in the dataset.
To identify missing values, we used functions like .isnull() and .sum().

A summary report was created to calculate:

Total missing values in each column
Percentage of missing values

This helps in understanding how much data is missing and which columns require cleaning.

In [4]:
import pandas as pd

df = pd.read_csv("health_data.csv")

missing_count = df.isnull().sum()
missing_percent = (missing_count / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Count": missing_count,
    "Percentage (%)": missing_percent
})

print(missing_report)

                Missing Count  Percentage (%)
patient_id                  0             0.0
age                        10            10.0
gender                     10            10.0
region                     10            10.0
bmi                        10            10.0
blood_pressure              0             0.0
cholesterol                10            10.0
glucose                    10            10.0
disease_risk                0             0.0

### 🔹 Q2. Apply imputation techniques and compare results
**✅ (a) Simple Imputer (Numerical - BMI)**

Missing values in BMI were replaced using mean (or median).
Mean imputation is useful when data is normally distributed.

In [6]:
df["bmi"] = df["bmi"].fillna(df["bmi"].mean())
df

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,1,58.0,Female,East,23.928378,111.660827,159.730615,NaN,0
1,2,71.0,Male,East,21.554029,118.083978,99.077134,91.479353,0
2,3,48.0,NaN,North,85.917497,96.591644,233.706253,125.509265,1
3,4,34.0,Male,West,21.904653,150.005221,264.296156,98.168679,0
4,5,62.0,Female,North,26.780799,101.998024,189.722334,118.741450,0
...,...,...,...,...,...,...,...,...,...
95,96,33.0,Female,West,27.338585,115.525482,176.627593,121.349123,0
96,97,50.0,Male,South,17.242830,113.830641,173.836887,114.229085,0
97,98,67.0,Male,West,22.447534,134.760353,179.869283,94.212441,0
98,99,34.0,Male,East,21.335244,121.553521,210.078462,71.695950,0
99,100,27.0,Male,West,25.976732,124.014540,214.832279,111.908023,0

**✅ (b) Simple Imputer (Categorical - Region)**

Missing values in region were filled using the most frequent value (mode).
This is suitable for categorical data.

In [ ]:
df["region"] = df["region"].fillna(df["region"].mode()[0])

,patient_id,age,gender,region,bmi,blood_pressure,cholesterol,glucose,disease_risk
0,1,58.0,Female,East,23.928378,111.660827,159.730615,NaN,0
1,2,71.0,Male,East,21.554029,118.083978,99.077134,91.479353,0
2,3,48.0,NaN,North,85.917497,96.591644,233.706253,125.509265,1
3,4,34.0,Male,West,21.904653,150.005221,264.296156,98.168679,0
4,5,62.0,Female,North,26.780799,101.998024,189.722334,118.741450,0
...,...,...,...,...,...,...,...,...,...
95,96,33.0,Female,West,27.338585,115.525482,176.627593,121.349123,0
96,97,50.0,Male,South,17.242830,113.830641,173.836887,114.229085,0
97,98,67.0,Male,West,22.447534,134.760353,179.869283,94.212441,0
98,99,34.0,Male,East,21.335244,121.553521,210.078462,71.695950,0
99,100,27.0,Male,West,25.976732,124.014540,214.832279,111.908023,0

**✅ (d) Missing Indicator + Random Sample Imputation**

A new column was created to indicate missing values.
Then missing values were replaced with random samples from existing data to maintain distribution.

In [8]:
# Indicator column
df["bmi_missing"] = df["bmi"].isnull().astype(int)

# Random sample imputation
random_sample = df["bmi"].dropna().sample(df["bmi"].isnull().sum(), random_state=42)
df.loc[df["bmi"].isnull(), "bmi"] = random_sample.values